In [35]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [36]:
a=tf.constant([1,2,3,1,1])
b=tf.constant([0,1,3,4,5])
c=tf.where(tf.greater(a,b),a,b) # 若a>b，返回a对应位置的元素，否则返回b对应位置的元素

In [37]:
c

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

In [38]:
rdm=np.random.RandomState(seed=1)
a=rdm.rand()
b=rdm.rand(2,3)

In [39]:
a

0.417022004702574

In [40]:
b

array([[7.20324493e-01, 1.14374817e-04, 3.02332573e-01],
       [1.46755891e-01, 9.23385948e-02, 1.86260211e-01]])

In [41]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.vstack((a,b))

In [42]:
d=np.hstack((a,b))
d

array([1, 2, 3, 4, 5, 6])

In [43]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
x,y=np.mgrid[1:3:1,2:4:0.5] # 生成等间隔数值点 

In [45]:
x

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.]])

In [46]:
y

array([[2. , 2.5, 3. , 3.5],
       [2. , 2.5, 3. , 3.5]])

In [47]:
x.ravel() # 将x拉直

array([1., 1., 1., 1., 2., 2., 2., 2.])

In [48]:
y.ravel()

array([2. , 2.5, 3. , 3.5, 2. , 2.5, 3. , 3.5])

In [49]:
# 将x, y拉直，并合并配对为二维张量，生成二维坐标点
grid=np.c_[x.ravel(),y.ravel()]
grid

array([[1. , 2. ],
       [1. , 2.5],
       [1. , 3. ],
       [1. , 3.5],
       [2. , 2. ],
       [2. , 2.5],
       [2. , 3. ],
       [2. , 3.5]])

#### 使用均方误差作为损失函数

In [50]:
## 使用均方误差作为损失函数
rdm=np.random.RandomState() # 生成[0,1)之间的随机数
x=rdm.rand(3,2) # x为生成3行2列并且数据在[0,1)之间的随机数

In [51]:
x

array([[0.11109202, 0.55807018],
       [0.34009063, 0.39887964],
       [0.10987777, 0.29229748]])

In [52]:
for x1,x2 in x:
    print(x1)
    print(x2)
    print("-----")

0.11109202492039383
0.5580701760912975
-----
0.3400906309575653
0.3988796423526333
-----
0.10987776852524322
0.2922974777925582
-----


In [53]:
y_ = [[x1 + x2 + (rdm.rand() / 10.0 - 0.05)] for (x1, x2) in x]   # 生成噪声[0,1)/10=[0,0.1); [0,0.1)-0.05=[-0.05,0.05)
y_

[[0.6599501369321633], [0.7269809834337161], [0.4041195353523103]]

In [54]:
x=tf.cast(x,dtype=tf.float32)

In [55]:
w1=tf.Variable(tf.random.normal([2,1],stddev=1,seed=1))

In [56]:
epoch=15000
lr=0.002 # 学习率
for epoch in range(epoch):
    with tf.GradientTape() as tape:
        y=tf.matmul(x,w1)
        loss_mse=tf.reduce_mean(tf.square(y_-y))
    grads=tape.gradient(loss_mse,w1)
    w1.assign_sub(lr*grads)
    if epoch%500==0:
        print("After %d training steps,w1 is " % (epoch))
        print(w1.numpy(),"\n")
print("Final w1 is: ",w1.numpy())

After 0 training steps,w1 is 
[[1.3588443 ]
 [0.54195863]] 

After 500 training steps,w1 is 
[[1.3836937 ]
 [0.63085437]] 

After 1000 training steps,w1 is 
[[1.3956923 ]
 [0.68995994]] 

After 1500 training steps,w1 is 
[[1.3995051]
 [0.7298117]] 

After 2000 training steps,w1 is 
[[1.3981383]
 [0.7572061]] 

After 2500 training steps,w1 is 
[[1.393528 ]
 [0.7765244]] 

After 3000 training steps,w1 is 
[[1.3869194]
 [0.7905944]] 

After 3500 training steps,w1 is 
[[1.3791134 ]
 [0.80123895]] 

After 4000 training steps,w1 is 
[[1.3706249 ]
 [0.80963564]] 

After 4500 training steps,w1 is 
[[1.3617822 ]
 [0.81654423]] 

After 5000 training steps,w1 is 
[[1.3527966]
 [0.8224566]] 

After 5500 training steps,w1 is 
[[1.3437976]
 [0.8276892]] 

After 6000 training steps,w1 is 
[[1.3348798 ]
 [0.83244836]] 

After 6500 training steps,w1 is 
[[1.3260841]
 [0.8368671]] 

After 7000 training steps,w1 is 
[[1.3174452 ]
 [0.84103227]] 

After 7500 training steps,w1 is 
[[1.3089839]
 [0.8450014]

#### 交叉熵损失函数

In [57]:
loss_ce1=tf.losses.categorical_crossentropy([1,0],[0.6,0.4])
loss_ce2=tf.losses.categorical_crossentropy([1,0],[0.8,0.2])

In [58]:
loss_ce1.numpy()

0.5108256

In [59]:
loss_ce2.numpy()

0.22314353

In [60]:
# softmax与交叉熵损失函数的结合
y_ = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 0, 0], [0, 1, 0]])
y = np.array([[12, 3, 2], [3, 10, 1], [1, 2, 5], [4, 6.5, 1.2], [3, 6, 1]])
y_pro = tf.nn.softmax(y)
loss_ce1 = tf.losses.categorical_crossentropy(y_,y_pro)
loss_ce2 = tf.nn.softmax_cross_entropy_with_logits(y_, y) # 相当于前两步的整合

In [61]:
loss_ce1.numpy()

array([1.68795487e-04, 1.03475622e-03, 6.58839038e-02, 2.58349207e+00,
       5.49852354e-02])

In [62]:
loss_ce2.numpy()

array([1.68795487e-04, 1.03475622e-03, 6.58839038e-02, 2.58349207e+00,
       5.49852354e-02])

In [63]:
xx,yy=np.mgrid[-3:3:0.01,-3:3:0.01]

In [64]:
xx

array([[-3.  , -3.  , -3.  , ..., -3.  , -3.  , -3.  ],
       [-2.99, -2.99, -2.99, ..., -2.99, -2.99, -2.99],
       [-2.98, -2.98, -2.98, ..., -2.98, -2.98, -2.98],
       ...,
       [ 2.97,  2.97,  2.97, ...,  2.97,  2.97,  2.97],
       [ 2.98,  2.98,  2.98, ...,  2.98,  2.98,  2.98],
       [ 2.99,  2.99,  2.99, ...,  2.99,  2.99,  2.99]])